baseURL = 'https://dots.ymajan.pw'
languageCode = 'en-us'
title = 'Dotfiles for Jaynam Shah'
theme = 'github.com/panr/hugo-theme-terminal'

[module]
  [[module.imports]]
    path = "github.com/panr/hugo-theme-terminal"

[params]
  # Terminal theme requires these
  fullWidthTheme = false
  centerTheme = true
  themeColor = "green"  # Options: orange, blue, red, green, pink
  showMenuItems = 2
  showLanguageSelector = false
  
  # Optional but useful
  enableEmoji = true
  enableGitInfo = false
  
  [params.twitter]
    # Even if empty, the theme expects this section
    creator = ""
    site = ""

[markup.goldmark.renderer]
  unsafe = true
